spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://todo-db.czqigmiuezli.ap-northeast-2.rds.amazonaws.com/mydatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    aws:
      region:
        static: ap-northeast-2
  config:
    import:
      - aws-parameterstore:/todo/config/